version: '3'

services:
  fastapi:
    build:
      context: ./app
    ports:
      - "8000:80"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    volumes:
      - ./app:/app
